workspace:
  base: /go
  path: src/git.ronmi.tw/ronmi/sdm

matrix:
  GOVER:
    - 1.5
    - 1.6
    - 1.7
    - 1.8

pipeline:
  go:
    image: golang:${GOVER}
    pull: true
    commands:
      - go get -t -v
      - go build -v
      - go test -v
